### ISSUE TITLE
Example data

### ISSUE THREAD

**Issue by PlantDr430** [auton1/LDhot#2]
Hello,

Can you clarify if the example files you provided are exaggerated or not? In your [2014 paper](https://arxiv.org/ftp/arxiv/papers/1403/1403.4264.pdf) you state that hotspots are approximately 2 kbp in length. However, in your example that you posted with the repository, the summary hotspot is actually 8.4 kbp in length.

```
#hotStart	hotEnd	p	rho_across_hotspot	peak_rate
45.7	54.1	0	93.3738	41.1452
```

Is this purposefully exaggerated just for the example?

**Comment by auton1** [comment]
No - the simulated hotspots were of 2kbp in length. I think what you're seeing here is the estimated width, and this is dependent on SNP density. LDhot cannot estimate a hotspot narrower than the two SNPs either side of the hotspot.
