### ISSUE TITLE
Multithreading: error n_threads not an option

### ISSUE THREAD

**Issue by ThomasBrazier** [auton1/LDhot#3]
Hi,
I'm looking to use 'ldhot' with multithreading to speed up a lot the analyses for a large dataset.

I compiled with 'Multi=1'. However I get the following error:
'Error: Unknown option: --n_threads'

'--n_threads' is in the list of parameters given by 'ldhot (v0.4)'.

Besides, even if I don't specify 'n_threads', LDhot is always running on a single core.

Thanks for your help,

Thomas Brazier

**Comment by aauton** [comment]
One comment is that it should be all caps: i.e. MULTI=1

The other comment is that the code relies on having OpenMP available on your system.

**Comment by ThomasBrazier** [comment]
Thanks, I used MULTI=1 since the beginning. The problem was not in LDhot but with the interaction of Snakemake and OpenMP. Snakemake was setting the number of threads to 1 unless explicitly setting a number of threads.

Nevertheless I still have the error 'Error: Unknown option: --n_threads' if I want to set --n_threads with the multi-threaded version of the tool (though it is an option offered in the --help of LDhot, maybe an old option from a previous version). LDhot take all available cores. It is not a problem for me, since I use a cluster and Snakemake to manage the number of cores, but it may be a problem for people running directly on their computer.
